--
-- PostgreSQL database dump
--

\restrict bt7KZZIfpW5xVKy3h5b8wDO59vIuGHDSFOjRhWiwAbBNdJcGPVUevNXn6xUl08s

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-22 18:17:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 17123)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17122)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17061)
-- Name: comment_likes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment_likes (
    id bigint NOT NULL,
    comment_id bigint NOT NULL,
    user_email character varying(255) NOT NULL
);


ALTER TABLE public.comment_likes OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17060)
-- Name: comment_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17070)
-- Name: comment_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment_reports (
    id bigint NOT NULL,
    comment_content text NOT NULL,
    comment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reason character varying(255) NOT NULL,
    reported_user_email character varying(255) NOT NULL,
    reported_user_name character varying(255) NOT NULL,
    reporter_email character varying(255) NOT NULL,
    reporter_name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT comment_reports_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IGNORED'::character varying, 'RESOLVED'::character varying])::text[])))
);


ALTER TABLE public.comment_reports OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17069)
-- Name: comment_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17089)
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    content text NOT NULL,
    coupon_granted boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    likes integer NOT NULL,
    parent_id bigint,
    product_id bigint NOT NULL,
    user_email character varying(255) NOT NULL,
    user_name character varying(255) NOT NULL
);


ALTER TABLE public.comments OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17088)
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17045)
-- Name: contact_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contact_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    message text NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255),
    status character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    CONSTRAINT contact_messages_status_check CHECK (((status)::text = ANY ((ARRAY['UNREAD'::character varying, 'READ'::character varying, 'REPLIED'::character varying])::text[])))
);


ALTER TABLE public.contact_messages OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17044)
-- Name: contact_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contact_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17105)
-- Name: coupons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    discount_percent integer NOT NULL,
    used boolean NOT NULL,
    user_email character varying(255) NOT NULL
);


ALTER TABLE public.coupons OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17104)
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16947)
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    quantity integer NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16946)
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16959)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    shipping_cost numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    order_number character varying(255) NOT NULL,
    shipping_address character varying(255) NOT NULL,
    shipping_city character varying(255) NOT NULL,
    shipping_email character varying(255) NOT NULL,
    shipping_first_name character varying(255) NOT NULL,
    shipping_last_name character varying(255) NOT NULL,
    shipping_phone character varying(255) NOT NULL,
    shipping_postal_code character varying(255) NOT NULL,
    shipping_province character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16958)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16990)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    is_oem boolean NOT NULL,
    original_price numeric(10,2),
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    condition character varying(255) NOT NULL,
    description text NOT NULL,
    image_url character varying(255),
    manufacturer character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    warranty character varying(255) NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16989)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17008)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    reset_token character varying(255),
    reset_token_expiry timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17007)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5104 (class 0 OID 17123)
-- Dependencies: 238
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, name) FROM stdin;
2	Cámaras frontales
\.


--
-- TOC entry 5096 (class 0 OID 17061)
-- Dependencies: 230
-- Data for Name: comment_likes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comment_likes (id, comment_id, user_email) FROM stdin;
1	1	fermarcor280304@gmail.com
2	2	fermarcor280304@gmail.com
3	1	LUCIA@GMAIL.COM
4	2	LUCIA@GMAIL.COM
5	1	admin@irenewhub.com
6	1	byfemar2803@gmail.com
7	3	fermarcor280304@gmail.com
8	1	nino1@gmail.com
\.


--
-- TOC entry 5098 (class 0 OID 17070)
-- Dependencies: 232
-- Data for Name: comment_reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comment_reports (id, comment_content, comment_id, created_at, reason, reported_user_email, reported_user_name, reporter_email, reporter_name, status) FROM stdin;
1	tienes razon me encantaaaaa	2	2026-04-26 13:44:33.47568	iNSULTO	fermarcor280304@gmail.com	Ignacio Martínez Cordero	LUCIA@GMAIL.COM	Lucia adwAEFCAWEF	IGNORED
2	Muy buen producto me encanta	1	2026-04-26 18:25:34.565685	zfvgesgveg	fermarcor280304@gmail.com	Ignacio Martínez Cordero	admin@irenewhub.com	Admin iRenewHub	IGNORED
3	deadass prdocut\n	3	2026-04-26 18:26:27.384454	enga	fermarcor280304@gmail.com	Ignacio Martínez Cordero	admin@irenewhub.com	Admin iRenewHub	RESOLVED
\.


--
-- TOC entry 5100 (class 0 OID 17089)
-- Dependencies: 234
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comments (id, content, coupon_granted, created_at, likes, parent_id, product_id, user_email, user_name) FROM stdin;
2	tienes razon me encantaaaaa	f	2026-04-26 13:43:39.933858	2	1	2	fermarcor280304@gmail.com	Ignacio Martínez Cordero
1	Muy buen producto me encanta	t	2026-04-26 13:43:28.253201	5	\N	2	fermarcor280304@gmail.com	Ignacio Martínez Cordero
\.


--
-- TOC entry 5094 (class 0 OID 17045)
-- Dependencies: 228
-- Data for Name: contact_messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contact_messages (id, created_at, email, message, name, phone, status, subject) FROM stdin;
5	2026-05-10 21:28:38.160665	byfemar2803@gmail.com	fsfdcscewscwcwscsewcsewcs	Fernando Martínez	111111111	UNREAD	qwwafcwacfwafcwasvdscs
\.


--
-- TOC entry 5102 (class 0 OID 17105)
-- Dependencies: 236
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.coupons (id, code, created_at, discount_percent, used, user_email) FROM stdin;
1	IRH-ABB3D4F9	2026-04-26 18:09:52.427052	5	t	fermarcor280304@gmail.com
3	IRH-TEST0002	2026-05-19 17:30:21.218276	5	f	fermarcor280304@gmail.com
4	IRH-TEST0003	2026-05-19 17:30:21.218276	5	f	fermarcor280304@gmail.com
2	IRH-TEST0001	2026-05-19 17:30:21.218276	5	t	fermarcor280304@gmail.com
\.


--
-- TOC entry 5086 (class 0 OID 16947)
-- Dependencies: 220
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (quantity, subtotal, unit_price, id, order_id, product_id) FROM stdin;
1	179.99	179.99	13	28	3
1	299.99	299.99	14	29	1
2	59.98	29.99	15	30	6
2	359.98	179.99	17	32	3
3	539.97	179.99	18	33	3
1	39.99	39.99	19	34	5
1	39.99	39.99	20	35	5
2	79.98	39.99	21	36	5
1	39.99	39.99	22	37	5
1	179.99	179.99	23	38	3
2	179.98	89.99	24	38	4
1	49.99	49.99	25	38	2
1	39.99	39.99	26	39	5
\.


--
-- TOC entry 5088 (class 0 OID 16959)
-- Dependencies: 222
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (shipping_cost, subtotal, total, created_at, id, user_id, order_number, shipping_address, shipping_city, shipping_email, shipping_first_name, shipping_last_name, shipping_phone, shipping_postal_code, shipping_province, status) FROM stdin;
0.00	179.99	179.99	2026-05-06 21:43:10.735161	28	2	IPH-71F987F3	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Valencia	PENDING
0.00	59.98	59.98	2026-05-07 10:44:24.334385	30	2	IPH-DE137BC4	1wefcwaefdcwfcfew	wedcwcw	fernando.martinezcordero@nervion.salesianas.org	Fernando	Martínez Cordero	111111111	11111	Sevilla	CONFIRMED
0.00	299.99	299.99	2026-05-07 10:14:18.247087	29	2	IPH-89BFF2F9	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Zaragoza	CONFIRMED
0.00	359.98	359.98	2026-05-08 19:21:32.213638	32	4	IPH-EE4DD28B	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Zaragoza	DELIVERED
0.00	539.97	539.97	2026-05-08 19:43:08.024653	33	4	IPH-EF78A89B	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Málaga	PENDING
4.99	39.99	44.98	2026-05-08 19:55:36.19396	34	4	IPH-6F44B107	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Málaga	CONFIRMED
4.99	39.99	44.98	2026-05-18 18:50:13.081273	35	4	IPH-F2CD74EF	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Barcelona	PENDING
4.99	39.99	44.98	2026-05-19 17:59:32.542432	39	4	IPH-0F04C8F8	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Barcelona	CONFIRMED
0.00	409.96	389.46	2026-05-19 17:35:39.326907	38	4	IPH-CD660072	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Sevilla	SHIPPED
4.99	39.99	44.98	2026-05-18 20:50:02.155811	37	4	IPH-16C4F0A1	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Sevilla	DELIVERED
0.00	79.98	79.98	2026-05-18 20:39:13.667583	36	4	IPH-2CB78F6C	Dos hermanas	Sevilla	byfemar2803@gmail.com	Fernando	Martínez	111111111	41700	Barcelona	CANCELLED
\.


--
-- TOC entry 5090 (class 0 OID 16990)
-- Dependencies: 224
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (is_oem, original_price, price, stock, id, category, condition, description, image_url, manufacturer, name, warranty) FROM stdin;
t	\N	89.99	6	15	Cámaras frontales	Nuevo	Módulo de repuesto original de la cámara frontal para iPhone 17 Pro. Ideal para sustituir lentes dañadas por caídas, sensores con píxeles muertos o fallos en el sistema de autoenfoque avanzado.\n• Resolución: Sensor de 24 MP con sistema avanzado de lentes de 6 elementos.\n• Compatibilidad: Diseñado exclusivamente para el modelo iPhone 17 Pro.\n• Rendimiento: Soporte completo para las últimas funciones de videollamadas espaciales y Face ID de nueva generación.	assets/products/cam_front_i17pro.webp	Apple	Cámara Frontal iPhone 17 Pro	12 meses
t	\N	99.99	6	12	Cámaras traseras	Nuevo	Módulo de repuesto completo OEM de la cámara trasera doble para iPhone 13 Pro Max. Reemplaza tu cámara si presenta manchas internas, fallos de enfoque, vibraciones continuas debido al estabilizador dañado o pantalla en negro.\n• Resolución: 12 MP (Gran angular y ultra gran angular).\n• Rendimiento: Grabación de vídeo 4K HDR idéntica a la pieza de fábrica.	assets/products/cam-tras-iphone-13promax.jpg	Apple	Camara Trasera iPhone 13 Pro Max	6 meses
t	249.99	179.99	99	3	Cámaras traseras	Nuevo	Sistema de cámara triple de 48MP. Incluye sensor principal, ultra gran angular y telefoto.	assets/products/camara-iphone-15-pro-max.jpg	Apple	Cámara Trasera iPhone 15 Pro Max	12 meses
t	\N	8.99	15	14	Altavoces y Auriculares	Nuevo	Altavoz interno superior para iPhone 11. Corrige problemas de audio distorsionado, sonido extremadamente bajo o ausencia total de voz durante las llamadas telefónicas tradicionales.\n• Sonido: Audio nítido y estéreo equilibrado.\n• Importante: Requiere soldadura del flex original si se desea mantener la función Face ID activa tras el cambio.	assets/products/altav-auric-iphone-13pro.jpg	Apple	Altavoz Auricular Superior iPhone 11	6 meses
t	\N	24.99	8	13	Conectores	Nuevo	Módulo flex de carga de repuesto para iPhone 12 Pro. Soluciona fallos de conexión con el cable Lightning, problemas de carga lenta, micrófono inferior inoperativo o mala recepción de antena.\n• Conector: Puerto Lightning reforzado.\n• Componentes: Incluye micrófono inferior y conexiones de antena.\n• Compatibilidad: Diseñado exclusivamente para los modelos iPhone 12 Pro (6.1 pulgadas).	assets/products/conector-iphone-12.jpg	Apple	Conector de Carga Flex iPhone 12 Pro	6 meses
t	\N	39.99	34	5	Conectores	Nuevo	Puerto de carga Lightning original. Incluye micrófono y cables flex.	assets/products/flex-conec-carg-iphone-16.jpg	Apple	Conector de Carga Lightning iPhone 16	6 meses
t	\N	69.99	29	16	Cámaras frontales	Nuevo	Módulo de repuesto de la cámara frontal (Selfie) para iPhone 15 Plus. Corrige fallos de enfoque, imágenes borrosas, pantalla en negro al abrir la cámara delantera o problemas con la integración de la Dynamic Island.\n• Resolución: 12 MP con apertura f/1.9 y autoenfoque.\n• Funciones: Compatible con grabación de vídeo 4K Cinemático.\n• Importante: El reemplazo de este módulo requiere conocimientos técnicos avanzados. Las funciones biométricas de Face ID pueden requerir calibración de software para mantenerse activas.	assets/products/cam-front-iphone-15plus.jpg	Apple	Cámara Frontal iPhone 15 Plus	3 meses
t	149.99	129.99	12	1	Pantallas	Nuevo	Pantalla OLED original certificada por Apple. Calidad premium con tecnología ProMotion 120Hz.	assets/products/pantalla-iphone-14-pro.webp	Apple	Pantalla OLED iPhone 14 Pro	12 meses
f	\N	19.99	20	11	Pantallas	Nuevo	Pantalla de repuesto económica con tecnología Incell para iPhone XR. Ofrece una excelente fidelidad de color, brillo óptimo y un grosor ultra fino que facilita una instalación perfecta sin holguras.\n• Tecnología: LCD Incell de alta resolución.\n• Tamaño: 6.1 pulgadas.\n• Táctil: Respuesta fluida y digitalizador de alta sensibilidad.\n• Ventaja: Consumo energético eficiente que no agota la batería.	assets/products/incel-pant-iphone-xr.webp	Nohon	Pantalla Incell iPhone XR	3 meses
f	\N	29.99	18	4	Pantallas	Reacondicionado	Pantalla LCD de alta calidad genérica. Certificada por Apple, excelente relación calidad-precio.	assets/products/pantalla-iphone-11.jpg	Nohon	Pantalla LCD iPhone 11 	6 meses
f	\N	49.99	26	2	Baterías	Nuevo	Batería de reemplazo con certificación Apple. Capacidad de 3227mAh.	assets/products/bateria-iphone-13.webp	Nohon	Batería iPhone 13	6 meses
t	\N	29.99	9	6	Altavoces y Auriculares	Nuevo	Altavoz superior para llamadas. Audio cristalino y compatible con Spatial Audio.	assets/products/altavoz-iphone-13-pro.jpg	Apple	Altavoz Auricular iPhone 13 Pro	3 meses
f	\N	24.99	15	10	Baterías	Nuevo	Batería de repuesto premium para iPhone 11 con celdas de alta calidad. Resuelve los problemas de descarga rápida y apagados inesperados, devolviendo la autonomía original a tu teléfono.\n• Capacidad: 2942 mAh (Igual a la original).\n• Componentes: Celdas de Ion de Litio de ciclo cero.\n• Protección: Chip IC integrado para evitar sobrecalentamientos y sobrecargas.\n• Nota: Tras la instalación, el sistema mostrará el aviso de "Pieza desconocida" debido al cifrado de Apple, lo cual no afecta a su rendimiento.	assets/products/bat-nohon-iphone-11.webp	Nohon	Bateria iPhone 11	3 meses
\.


--
-- TOC entry 5092 (class 0 OID 17008)
-- Dependencies: 226
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, first_name, last_name, password, role, reset_token, reset_token_expiry) FROM stdin;
2	admin@irenewhub.com	Admin	iRenewHub	$2a$10$KfgulqbCF/cMrPWBaCzUAuIkmdIlCoWz8GvqckfS03gppkpWf2m5.	ADMIN	\N	\N
7	nino1@gmail.com	nono	ascwascawc	$2a$10$DfpNmF2brIxgQyIzzrE5r.zPVnOIouf6Z8bcBDAlTGgv7xul2yHk2	USER	\N	\N
4	fermarcor280304@gmail.com	Fernando	Martínez Cordero	$2a$10$l65dAFBfA3cUUNEC0g6EN.YvdhmEzd071NA/EjiPvI4Q9L8Q54xLq	USER	\N	\N
6	byfemar2803@gmail.com	wsecwsacfawc	wasccwcwew	$2a$10$S9bsXTHK9vEVyjCWiA1OLOSletVIOSJaTeRpvWF1szy3tLbgWXxgO	USER	bc77c317-8423-4c78-be7d-ec8f693e44a8	2026-05-18 20:10:03.738735
\.


--
-- TOC entry 5110 (class 0 OID 0)
-- Dependencies: 237
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 2, true);


--
-- TOC entry 5111 (class 0 OID 0)
-- Dependencies: 229
-- Name: comment_likes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comment_likes_id_seq', 8, true);


--
-- TOC entry 5112 (class 0 OID 0)
-- Dependencies: 231
-- Name: comment_reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comment_reports_id_seq', 3, true);


--
-- TOC entry 5113 (class 0 OID 0)
-- Dependencies: 233
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comments_id_seq', 3, true);


--
-- TOC entry 5114 (class 0 OID 0)
-- Dependencies: 227
-- Name: contact_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contact_messages_id_seq', 5, true);


--
-- TOC entry 5115 (class 0 OID 0)
-- Dependencies: 235
-- Name: coupons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.coupons_id_seq', 5, true);


--
-- TOC entry 5116 (class 0 OID 0)
-- Dependencies: 219
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_id_seq', 26, true);


--
-- TOC entry 5117 (class 0 OID 0)
-- Dependencies: 221
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 39, true);


--
-- TOC entry 5118 (class 0 OID 0)
-- Dependencies: 223
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 16, true);


--
-- TOC entry 5119 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- TOC entry 4932 (class 2606 OID 17129)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4920 (class 2606 OID 17068)
-- Name: comment_likes comment_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT comment_likes_pkey PRIMARY KEY (id);


--
-- TOC entry 4924 (class 2606 OID 17087)
-- Name: comment_reports comment_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_reports
    ADD CONSTRAINT comment_reports_pkey PRIMARY KEY (id);


--
-- TOC entry 4926 (class 2606 OID 17103)
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- TOC entry 4918 (class 2606 OID 17059)
-- Name: contact_messages contact_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact_messages
    ADD CONSTRAINT contact_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 4928 (class 2606 OID 17117)
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 16957)
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4908 (class 2606 OID 16984)
-- Name: orders orders_order_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_order_number_key UNIQUE (order_number);


--
-- TOC entry 4910 (class 2606 OID 16982)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4912 (class 2606 OID 17006)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 4922 (class 2606 OID 17119)
-- Name: comment_likes uk95q8m30d311t470pcxd9312w7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT uk95q8m30d311t470pcxd9312w7 UNIQUE (comment_id, user_email);


--
-- TOC entry 4930 (class 2606 OID 17121)
-- Name: coupons ukeplt0kkm9yf2of2lnx6c1oy9b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukeplt0kkm9yf2of2lnx6c1oy9b UNIQUE (code);


--
-- TOC entry 4934 (class 2606 OID 17131)
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- TOC entry 4914 (class 2606 OID 17023)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4916 (class 2606 OID 17021)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4937 (class 2606 OID 17034)
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4935 (class 2606 OID 17024)
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- TOC entry 4936 (class 2606 OID 17029)
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);


-- Completed on 2026-05-22 18:17:02

--
-- PostgreSQL database dump complete
--

\unrestrict bt7KZZIfpW5xVKy3h5b8wDO59vIuGHDSFOjRhWiwAbBNdJcGPVUevNXn6xUl08s

