# =============================================
# BASE DE DATOS - PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/irenewhub
spring.datasource.username=postgres
spring.datasource.password=280304
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / HIBERNATE
# =============================================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =============================================
# SERVIDOR
# =============================================
server.port=8080

# =============================================
# APP
# =============================================
spring.application.name=irenewhub-backend